# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'STYLiSH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STYLiSH
pod 'Kingfisher', '~> 5.7' 
pod 'CRRefresh'
pod 'Alamofire', '~> 5.0.0-beta.5'
pod "ESPullToRefresh"
pod 'SwiftLint'
pod 'IQKeyboardManagerSwift'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'KeychainAccess'




end
